version: 1.0.{build}
environment:
  version: 1.0.{build}
nuget:
  project_feed: true
before_build:
- cmd: nuget restore .\eXtremeNet.sln
build:
  publish_nuget: true  
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: XDyu2Wr5aDX3OW1GTJTSIq2y5wq5q8OFX9gJEHiRdwHGmCKNki/fI0vREBq1zYWR
  artifact: /.*\.nupkg/
